// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwpt5qJhH1xCW6EzGFdLmeaDQHOY_z6k',
    appId: '1:79550369447:web:a660cb157c354c56e49582',
    messagingSenderId: '79550369447',
    projectId: 'scottenex-attendance',
    authDomain: 'scottenex-attendance.firebaseapp.com',
    storageBucket: 'scottenex-attendance.firebasestorage.app',
    measurementId: 'G-RGH0VXVZN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwMAoH52mkUsmZjggJBPEu-pA_S7yqvfI',
    appId: '1:79550369447:android:731751c59e90fe99e49582',
    messagingSenderId: '79550369447',
    projectId: 'scottenex-attendance',
    storageBucket: 'scottenex-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-tZOOeFL2839qYRtMySUi0DLc0Qs_Ek',
    appId: '1:79550369447:ios:6b018a3c5cdf75bbe49582',
    messagingSenderId: '79550369447',
    projectId: 'scottenex-attendance',
    storageBucket: 'scottenex-attendance.firebasestorage.app',
    iosBundleId: 'com.example.scottenexAttendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-tZOOeFL2839qYRtMySUi0DLc0Qs_Ek',
    appId: '1:79550369447:ios:6b018a3c5cdf75bbe49582',
    messagingSenderId: '79550369447',
    projectId: 'scottenex-attendance',
    storageBucket: 'scottenex-attendance.firebasestorage.app',
    iosBundleId: 'com.example.scottenexAttendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOwpt5qJhH1xCW6EzGFdLmeaDQHOY_z6k',
    appId: '1:79550369447:web:0a2cf8c5ac2954d9e49582',
    messagingSenderId: '79550369447',
    projectId: 'scottenex-attendance',
    authDomain: 'scottenex-attendance.firebaseapp.com',
    storageBucket: 'scottenex-attendance.firebasestorage.app',
    measurementId: 'G-Z9KGR8MRSE',
  );
}
